version: '3'
services:
  db:
    image: mariadb:10
    container_name: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: "${DB_NAME}" #YAML 파일 외부로부터 환경변수를 주입받을 때, 그 값이 주입될 부분은 ${변수명} 또는 $변수명의 형태로 명시하도록 한다.
      MARIADB_USER: "${DB_USER_ID}"
      MARIADB_PASSWORD: "${DB_USER_PASSWORD}" 
      MARIADB_ROOT_PASSWORD: "${DB_USER_PASSWORD}" 
    volumes:
      - "./mariadb/conf.d:/etc/mysql/conf.d"
      - "./mariadb/data:/var/lib/mysql"