import Head from 'next/head';
import styled from 'styled-components';

export default function Home() {
  return (
    <Container>
      <Head>
        <title>write-ing blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>write-ing blog</h1>
    </Container>
  );
}

const Container = styled.div``